### PR TITLE
added new projections

### PR DESCRIPTION
**Pull request by filefolder**
small update to add some new NLL7 projections. I have only tested azimuthal_equidist but it should be the same as trans_mercator.

### CODE REVIEW

**Comment by claudiodsf** [comment]
Thank you for this PR!

I just pushed a small commit to fix coding stile.

I'm also planning to simplify the code by removing repetitions.

**Comment by filefolder** [comment]
all good! btw i have now tested both and as far as I can tell they are worked as expected. the differences are very very minor.

**Comment by claudiodsf** [comment]
Just pushed the new version. Could you please try it? (I didn't test it 🙄)

**Comment by filefolder** [comment]
have not tested the actual eq relocations with it  but the functionality (writing, project / iproject, etc) works as expected. cheers. 

I will be using it a lot next few weeks, if anything seems askew I will report back

**Comment by claudiodsf** [comment]
Ok, so I'll wait for your green light before merging this 😉

**Comment by filefolder** [comment]
OK confirmed all working, figures/comparisons between simple, lambert, azimuthal_equidist, and trans_merc in the last post of this issue: https://github.com/alomax/NonLinLoc/issues/17

**Comment by claudiodsf** [comment]
Great! Merged!

**Pull request merged**
